### ISSUE TITLE
Placeholder api error in llama economy and butcher 

### ISSUE THREAD

**Issue by Sreeraj-S** [llamadevelopment/LlamaEconomy#2]
Throwing
java.lang.RuntimeException: java.lang.IncompatibleClassChangeError: Found class com.creeperface.nukkit.placeholderapi.api.PlaceholderAPI, but interface was expected
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [cloudburst.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:748) [cloudburst.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:737) [cloudburst.jar:?]
        at cn.nukkit.Server.<init>(Server.java:580) [cloudburst.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [cloudburst.jar:?]
Caused by: java.lang.IncompatibleClassChangeError: Found class com.creeperface.nukkit.placeholderapi.api.PlaceholderAPI, but interface was expected
        at net.lldv.llamabutcher.LlamaButcher.placeholder(LlamaButcher.java:87) ~[?:?]
        at net.lldv.llamabutcher.LlamaButcher.lambda$onEnable$0(LlamaButcher.java:70) ~[?:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_275]
        at net.lldv.llamabutcher.LlamaButcher.onEnable(LlamaButcher.java:66) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[cloudburst.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[cloudburst.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[cloudburst.jar:?]
        ... 4 more

above is the error... same error for both economy and butcher

( putting the error here due to discord server link given was not working)

**Comment by Sreeraj-S** [comment]
This error was gone when the placeholder API was installed by the scoreboard plugin by Petteri.  

Thank you for your time helping

**Comment by RealTriassic** [comment]
This is due to PlaceholderAPI deciding to update and not keeping compatibility with older plugins, therefore alot of plugins that use PlaceholderAPI are having issues with it since they haven't updated
